---
- hosts: db
  become: yes
  vars_files:
    - vars_files/db.yml
  roles:
    - postgres_cookbook

- hosts: web
  become: yes
  vars_files:
    - vars_files/db.yml
  vars:
    - home_cookbook: /srv/cookbook
    - app_home_cookbook: /srv/cookbook/repo
  roles:
    - setup_web
    - install_app

- hosts: web[0]
  become: yes
  vars:
    - home_cookbook: /srv/cookbook
    - app_home_cookbook: /srv/cookbook/repo
  tasks:
    - name: Run migrations
      shell: "/bin/bash -lc 'bundle exec rake db:migrate'"
      become: yes
      become_user: cookbook
      args:
        chdir: '{{ app_home_cookbook }}'

- hosts: web
  become: yes
  tasks:
    - name: start/restart service
      systemd:
        name: cookbook
        state: restarted

- hosts: nginx
  become: yes
  vars:
    - cookbook_host: cookbook.com.br
    - cookbook_home_dir: /srv/cookbook/repo
  roles:
    - nginx
