---
- hosts: all
  become: yes
  roles:
    - weareinteractive.ufw
    - geerlingguy.security
    - geerlingguy.ntp
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

- hosts: db
  become: yes
  vars_files:
    - vars_files/db.yml
  roles:
    - geerlingguy.postgresql

- hosts: web
  become: yes
  vars_files:
    - vars_files/db.yml
  roles:
    - setup_web
    - install_app

- hosts: web[0]
  become: yes
  tasks:
    - name: Run migrations
      shell: "/bin/bash -lc 'bundle exec rake db:migrate'"
      become: yes
      become_user: cookbook
      args:
        chdir: '{{ app_home_cookbook }}'

- hosts: web
  become: yes
  tasks:
    - name: start/restart service
      systemd:
        name: cookbook
        state: restarted

- hosts: nginx
  become: yes
  roles:
    - nginx
