- name: Install Dependencies
  apt: name={{ packages }} state=present update_cache=true
  vars:
    packages:
      - python3-dev
      - libpq-dev
      - python3-psycopg2

- name: Install postgresql
  apt:
    name: postgresql
    state: present

- name: Add app user
  become_user: postgres
  postgresql_user:
    name: '{{ cookbook_db_user }}'
    password: '{{ cookbook_db_password }}'
    role_attr_flags: CREATEDB

- name: Ensure databases is present.
  postgresql_db:
    name: cookbook
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    encoding: 'UTF-8'
    template: 'template0'
    login_host: 'localhost'
    login_user: '{{ cookbook_db_user }}'
    login_password: '{{ cookbook_db_password }}'
    owner: '{{ cookbook_db_user }}'
    state: 'present'
